namespace SampleProjectCore.Mixins
{
    [System.ComponentModel.DescriptionAttribute("Generated by SharpILMixins")]
    public static class ProgramBruhTargets
    {
        public static class Methods
        {
            public const string Main = "System.Void SampleProject.ProgramBruh::Main(System.String[])";
            public static class MainInjects
            {
                public const string String_Format_String_Object = "System.String System.String::Format(System.String,System.Object)";
                public const string Console_WriteLine_String = "System.Void System.Console::WriteLine(System.String)";
                public const string ProgramBruh_BooleanOverload_Boolean = "System.Boolean SampleProject.ProgramBruh::BooleanOverload(System.Boolean)";
                public const string _coolNumber = "System.Int32 SampleProject.ProgramBruh::_coolNumber";
            }

            public const string BooleanOverload = "System.Boolean SampleProject.ProgramBruh::BooleanOverload(System.Boolean)";
            public static class BooleanOverloadInjects
            {
                public const string Boolean_Equals_Boolean = "System.Boolean System.Boolean::Equals(System.Boolean)";
            }

            public const string RandomNumber = "System.Int32 SampleProject.ProgramBruh::RandomNumber()";
        }
    }

    [System.ComponentModel.DescriptionAttribute("Generated by SharpILMixins")]
    public static class SomeGameClassTargets
    {
        public static class Methods
        {
            public const string DoSomething = "System.Int32 SampleProjectCore.SomeGameClass::DoSomething()";
            public static class DoSomethingInjects
            {
                public const string isRunning = "System.Boolean SampleProjectCore.SomeGameClass::isRunning";
                public const string counter = "System.Int32 SampleProjectCore.SomeGameClass::counter";
            }
        }
    }

    [System.ComponentModel.DescriptionAttribute("Generated by SharpILMixins")]
    public static class InjectClassTargets
    {
        public static class Methods
        {
            public const string Example = "System.Void SampleProjectCore.InjectClass::Example()";
            public static class ExampleInjects
            {
                public const string Console_WriteLine_String = "System.Void System.Console::WriteLine(System.String)";
                public const string Random_Next = "System.Int32 System.Random::Next()";
                public const string Math_Abs_Double = "System.Double System.Math::Abs(System.Double)";
                public const string _d = "System.Double SampleProjectCore.InjectClass::_d";
                public const string Random_ctor = "System.Void System.Random::.ctor()";
            }
        }
    }

    [System.ComponentModel.DescriptionAttribute("Generated by SharpILMixins")]
    public static class RedirectClassTargets
    {
        public static class Methods
        {
            public const string Example = "System.Void SampleProjectCore.RedirectClass::Example()";
            public static class ExampleInjects
            {
                public const string Console_WriteLine_Object = "System.Void System.Console::WriteLine(System.Object)";
                public const string Random_Next = "System.Int32 System.Random::Next()";
                public const string Math_Abs_Double = "System.Double System.Math::Abs(System.Double)";
                public const string _d = "System.Double SampleProjectCore.RedirectClass::_d";
                public const string StringWrapper_ctor_String = "System.Void SampleProjectCore.StringWrapper::.ctor(System.String)";
                public const string Random_ctor = "System.Void System.Random::.ctor()";
            }
        }
    }
}