namespace SampleProjectCore.Mixins
{
    [System.ComponentModel.DescriptionAttribute("Generated by SharpILMixins")]
    public static class ProgramBruhTargets
    {
        public static class Methods
        {
            public const string Main = "System.Void SampleProject.ProgramBruh::Main(System.String[])";
            public static class MainInjects
            {
                public const string String_Format_String_Object = "System.String System.String::Format(System.String,System.Object)";
                public const string Console_WriteLine_String = "System.Void System.Console::WriteLine(System.String)";
                public const string ProgramBruh_BooleanOverload_Boolean = "System.Boolean SampleProject.ProgramBruh::BooleanOverload(System.Boolean)";
                public const string _coolNumber = "System.Int32 SampleProject.ProgramBruh::_coolNumber";
            }

            public const string BooleanOverload = "System.Boolean SampleProject.ProgramBruh::BooleanOverload(System.Boolean)";
            public static class BooleanOverloadInjects
            {
                public const string Boolean_Equals_Boolean = "System.Boolean System.Boolean::Equals(System.Boolean)";
            }

            public const string RandomMethod = "System.Void SampleProject.ProgramBruh::RandomMethod(System.Boolean,System.Int32,SampleProjectCore.RandomEnum,System.Single,System.Int32)";
            public static class RandomMethodInjects
            {
                public const string Int32_Get_Int32_Int32 = "System.Int32 System.Int32[0...,0...]::Get(System.Int32,System.Int32)";
                public const string RandomEnum_Get_Int32_Int32 = "SampleProjectCore.RandomEnum SampleProjectCore.RandomEnum[0...,0...]::Get(System.Int32,System.Int32)";
                public const string RandomClass_Get_Int32_Int32 = "SampleProjectCore.RandomClass SampleProjectCore.RandomClass[0...,0...]::Get(System.Int32,System.Int32)";
                public const string Dictionary_2_ContainsKey_TKey = "System.Boolean System.Collections.Generic.Dictionary`2<System.Int32,SampleProjectCore.RandomClass>::ContainsKey(System.Int32)";
                public const string Console_WriteLine_Int32 = "System.Void System.Console::WriteLine(System.Int32)";
                public const string COOL_NUMBER_2D_ARRAY = "System.Int32[0...,0...] SampleProject.ProgramBruh::COOL_NUMBER_2D_ARRAY";
                public const string COOL_RANDOM_ARRAY = "SampleProjectCore.RandomEnum[0...,0...] SampleProject.ProgramBruh::COOL_RANDOM_ARRAY";
                public const string COOL_RANDOM2_ARRAY = "SampleProjectCore.RandomClass[0...,0...] SampleProject.ProgramBruh::COOL_RANDOM2_ARRAY";
                public const string COOL_RANDOM_DICTIONARY = "System.Collections.Generic.Dictionary`2<System.Int32,SampleProjectCore.RandomClass> SampleProjectCore.SomeGameClass::COOL_RANDOM_DICTIONARY";
            }

            public const string RandomNumber = "System.Int32 SampleProject.ProgramBruh::RandomNumber()";
        }
    }

    [System.ComponentModel.DescriptionAttribute("Generated by SharpILMixins")]
    public static class SomeGameClassTargets
    {
        public static class Methods
        {
            public const string DoSomething = "System.Int32 SampleProjectCore.SomeGameClass::DoSomething()";
            public static class DoSomethingInjects
            {
                public const string isRunning = "System.Boolean SampleProjectCore.SomeGameClass::isRunning";
                public const string counter = "System.Int32 SampleProjectCore.SomeGameClass::counter";
            }
        }
    }

    [System.ComponentModel.DescriptionAttribute("Generated by SharpILMixins")]
    public static class InjectClassTargets
    {
        public static class Methods
        {
            public const string WeirdExample = "System.Object SampleProjectCore.InjectClass::WeirdExample(System.Object)";
            public const string Example = "System.Void SampleProjectCore.InjectClass::Example()";
            public static class ExampleInjects
            {
                public const string Console_WriteLine_String = "System.Void System.Console::WriteLine(System.String)";
                public const string Random_Next = "System.Int32 System.Random::Next()";
                public const string Math_Abs_Double = "System.Double System.Math::Abs(System.Double)";
                public const string _d = "System.Double SampleProjectCore.InjectClass::_d";
                public const string Random_ctor = "System.Void System.Random::.ctor()";
            }
        }
    }

    [System.ComponentModel.DescriptionAttribute("Generated by SharpILMixins")]
    public static class RedirectClassTargets
    {
        public static class Methods
        {
            public const string Example = "System.Void SampleProjectCore.RedirectClass::Example()";
            public static class ExampleInjects
            {
                public const string Console_WriteLine_Object = "System.Void System.Console::WriteLine(System.Object)";
                public const string Console_WriteLine_String = "System.Void System.Console::WriteLine(System.String)";
                public const string Random_Next = "System.Int32 System.Random::Next()";
                public const string Math_Abs_Double = "System.Double System.Math::Abs(System.Double)";
                public const string _d = "System.Double SampleProjectCore.RedirectClass::_d";
                public const string StringWrapper_ctor_String = "System.Void SampleProjectCore.StringWrapper::.ctor(System.String)";
                public const string Random_ctor = "System.Void System.Random::.ctor()";
            }
        }
    }

    [System.ComponentModel.DescriptionAttribute("Generated by SharpILMixins")]
    public static class YieldReturnClassTargets
    {
        public static class Methods
        {
            public const string GetSomething = "System.Collections.Generic.IEnumerable`1<System.Object> SampleProjectCore.YieldReturnClass::GetSomething()";
            public const string GetSomething_StateMachine = "SampleProjectCore.YieldReturnClass/<GetSomething>d__0";
            public const string GetSomething_StateMachine_Method = "MoveNext";
            public static class GetSomethingInjects
            {
                public const string _GetSomething_d_0_ctor_Int32 = "System.Void SampleProjectCore.YieldReturnClass/<GetSomething>d__0::.ctor(System.Int32)";
            }
        }
    }
}